### ISSUE TITLE
Update to Protobuf 2.6.1 (maybe even provide a version for 3.0.0-alpha-1)

### ISSUE THREAD

**Issue by lambdaupb** [os72/protoc-jar-maven-plugin#1]
Hi,

it would be really nice, if this plugin could be updated.

Thanks for your awesome work :)

**Comment by os72** [comment]
Hi, I've made one more Linux build, I wonder if you could try it? Version 2.6.1.3. Thanks!

**Comment by lambdaupb** [comment]
Happy new year!

Works for me (linux amd64 1.8.0_25) :)

**Comment by os72** [comment]
Great, thanks! Happy New Year

**Comment by seh** [comment]
This issue had mentioned covering the 3.0 alpha as well, but the release in December 2014 didn't include it. I'll file a new issue for that request.
