### ISSUE TITLE
running protoc once for all input protos

### ISSUE THREAD

**Issue by thesamet** [os72/protoc-jar-maven-plugin#110]
It appears that the plugin invokes protoc individually for each source proto file. protoc is able to handle multiple source files in the command line. 

Is this intentional? Is there an option for protoc-jar-maven-plugin to pass all the input source filenames to protoc at once?

**Comment by os72** [comment]
Also #106

**Comment by thesamet** [comment]
Looks like I didn't notice the other ticket before I filed this one. Looks like a duplicate - closing.
