### ISSUE TITLE
Performance with multiple proto files

### ISSUE THREAD

**Issue by ibauersachs** [os72/protoc-jar-maven-plugin#13]
Currently protoc is extracted for every every .proto file. This extraction can be rather slow and it would be better to reuse the first extracted protoc for the following files. 

It is based around
- adding `runProtoc(String[][] cmds)` to protoc-jar (array of array of args), calling runProtoc(cmd, args)
- calling this new runProtoc from protoc-jar-maven-plugin

Caveat: the protoc-version must be the same for all files. This shouldn't be an issue: if a file(-set) needs a different version, the plugin can be added as often as needed with specific versions into the Maven build.

I have a local patch that needs some refinement - I'll create a PR if you like the idea.

**Comment by os72** [comment]
Is it worth it? But happy to see an implementation

**Comment by os72** [comment]
Please see commit https://github.com/os72/protoc-jar-maven-plugin/commit/9798debafa8e488f7b5630d69ae70edbf97febd4

**Comment by os72** [comment]
Could you give it a try? (Thanks!)

**Comment by ibauersachs** [comment]
Sorry for the late reply: yes, 9798debafa8e488f7b5630d69ae70edbf97febd4 works fine!

**Comment by os72** [comment]
Released 3.0.0.1
