### ISSUE TITLE
Restrict the plugin from cleaning generated sources

### ISSUE THREAD

**Issue by ravindarkumar** [os72/protoc-jar-maven-plugin#15]
I have some pre-activities (generate sources by other means) which i am doing before the proto files are compiled. But it seems like the plugin always clears the generated sources folder before compiling the protos. Is there a way to restrict that?

Thanks
Ravi

**Comment by os72** [comment]
Yes, `cleanOutputFolder`
http://os72.github.io/protoc-jar-maven-plugin/run-mojo.html

Are you using an older version? `cleanOutputFolder` default used to be true, switched to false a while back
https://github.com/os72/protoc-jar-maven-plugin/blob/master/RELEASE_NOTES.md

**Comment by ravindarkumar** [comment]
Urgh...... Wonder how I missed that page.

Thanks for the prompt response.

**Comment by paulvi** [comment]
ref #24

**Comment by paulvi** [comment]
> Are you using an older version? cleanOutputFolder default used to be true, switched to false a while back
https://github.com/os72/protoc-jar-maven-plugin/blob/master/RELEASE_NOTES.md

Well, I think `true` should it be.

And changing defaults is never nice.
