### ISSUE TITLE
Question: Integration within Eclipse IDE

### ISSUE THREAD

**Issue by paulvi** [os72/protoc-jar-maven-plugin#18]
For this maven-plugin to automatically run inside Eclipse, I guess a m2e connector is needed.
I found one https://github.com/masterzen/m2e-protoc-connector, but this plugin is not supported https://github.com/masterzen/m2e-protoc-connector/issues/7

Can you reference in README proper use within Eclipse (so that developers don't need to run `mvn generate-source` from command line after edits)

**Comment by os72** [comment]
It runs automatically, give it a try. (m2e mapping is included)

**Comment by paulvi** [comment]
It worked

http://stackoverflow.com/questions/40426366/automatically-generate-java-from-proto-with-maven-m2e-in-eclipse-ide

**Comment by paulvi** [comment]
I think README should be updated to mention that.

**Comment by JacksonBailey** [comment]
@os72 when I modify a proto file the java files aren't being updated. If I clean the Eclipse project they are correctly rebuilt. Is this the correct behavior or is there something I'm missing? It's almost like it's not scanning for changes.

(I can open a separate issue if you want, it just seemed sort of on topic here.)

**Comment by os72** [comment]
Try `<cleanOutputFolder>true</cleanOutputFolder>`

It's not super-reliable without running project-clean. I'm not an Eclipse expert, if it can be improved please let me know

**Comment by paulvi** [comment]
@os72 I created wiki page https://github.com/os72/protoc-jar-maven-plugin/wiki/Eclipse . It would be better place for now.

@JacksonBailey For re-generation just added http://stackoverflow.com/questions/40575671/automatically-refresh-generated-source-in-eclipse-and-maven
I guess maven plugin can't do that is purely IDE features like incremental build or compiling/re-generated on for files being edited.

**Comment by os72** [comment]
Closing
