### ISSUE TITLE
Can you enable this plugin to generate source files for python as well ? 

### ISSUE THREAD

**Issue by ravidutta** [os72/protoc-jar-maven-plugin#2]
You can follow the python package format that these guys are doing (https://github.com/urbanairship/mvn-python-packaging) or come up with your own format ? 
My use case is that I want a handshake package that I want to provide to the external party so that they have all the necessary files to build the protobuf message in any supported language (Java, C++, Python etc)

**Comment by os72** [comment]
Generating python source sounds good, will have a look. Didn't know python folks use maven too..

**Comment by os72** [comment]
Released new versions (2.4.1.4, 2.5.0.4, 2.6.1.4), all protoc output targets are now supported: java, cpp, python, descriptor. Please check out the documentation and let me know if it works
