### ISSUE TITLE
Different output comparing to protobuf-maven-plugin

### ISSUE THREAD

**Issue by paulvi** [os72/protoc-jar-maven-plugin#20]
Different output comparing to `org.xolstice.maven.plugins:protobuf-maven-plugin`

I just did simple test, and I found that this plugin did not generated `GreeterGrpc.java`

sources at 
- https://github.com/paulvi/com.example.grpc.maven
- https://github.com/paulvi/com.example.grpc.protoc-jar-maven-plugin

![image](https://cloud.githubusercontent.com/assets/1614482/20182911/62c7bd1c-a79e-11e6-94d0-6110f3c5bf37.png)

```xml
		<plugins>
			<plugin>
				<groupId>org.xolstice.maven.plugins</groupId>
				<artifactId>protobuf-maven-plugin</artifactId>
				<version>0.5.0</version>
				<configuration>
					<protocArtifact>com.google.protobuf:protoc:3.1.0:exe:${os.detected.classifier}</protocArtifact>
					<pluginId>grpc-java</pluginId>
					<pluginArtifact>io.grpc:protoc-gen-grpc-java:1.0.1:exe:${os.detected.classifier}</pluginArtifact>
				</configuration>
				<executions>
					<execution>
						<goals>
							<goal>compile</goal>
							<goal>compile-custom</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
		</plugins>
```

```xml
		<plugins>
			<plugin>
				<groupId>com.github.os72</groupId>
				<artifactId>protoc-jar-maven-plugin</artifactId>
				<version>3.1.0.1</version>
				<executions>
					<execution>
						<phase>generate-sources</phase>
						<goals>
							<goal>run</goal>
						</goals>
						<configuration>
							<protocVersion>3.1.0</protocVersion>
							<inputDirectories>
								<include>src/main/proto</include>
							</inputDirectories>
						</configuration>
					</execution>
				</executions>
			</plugin>
		</plugins>

```

**Comment by paulvi** [comment]
I see that `io.grpc:protoc-gen-grpc-java` is not in `protoc-jar-maven-plugin` configuration. How to add it?

**Comment by os72** [comment]
Try `<pluginPath>protoc-gen-grpc-java.exe</pluginPath>`
See http://os72.github.io/protoc-jar-maven-plugin/run-mojo.html

You might need a `grpc-java` outputTarget, not sure. Please give it a try

```
        <outputTarget>
                <type>grpc-java</type>
                <addSources>none</addSources>
                <cleanOutputFolder>false</cleanOutputFolder>
                <outputDirectory>lib/protobuf</outputDirectory>
                <pluginPath>protoc-gen-grpc-java.exe</pluginPath>
        </outputTarget
```

**Comment by paulvi** [comment]
That failed over file name I guess, see separate issue #23

**Comment by os72** [comment]
`protoc-gen-grpc-java.exe` (or other protoc plugin) execution works, but requires separate installation for now. May look into `protobuf-maven-plugin` style artifact download at some point

**Comment by os72** [comment]
Issue #27 will address `protoc-gen-grpc-java.exe` automatic installation
