### ISSUE TITLE
Have default <protocVersion>

### ISSUE THREAD

**Issue by paulvi** [os72/protoc-jar-maven-plugin#22]
as this plugin versioning follows protobuf versions,  it can have defaults.
E.g. 3.1.0.1 -> 3.1.0

result together with #21  will be no need for `<configuration>` section at all in the simplest case.

**Comment by os72** [comment]
Released 3.1.0.2

**Comment by paulvi** [comment]
Well, this issue was not addressed, I guess.

http://os72.github.io/protoc-jar-maven-plugin/run-mojo.html still does not mention default version

**Comment by os72** [comment]
It's implemented. Forgot to update doc but it's mentioned in release notes
https://github.com/os72/protoc-jar-maven-plugin/blob/master/RELEASE_NOTES.md

**Comment by paulvi** [comment]
few people read README, and even less RELEASE_NOTES
