### ISSUE TITLE
What is protoc plugins?

### ISSUE THREAD

**Issue by paulvi** [os72/protoc-jar-maven-plugin#25]
as mentioned by @os72 in #9 #23

> I'm not so familiar with protoc plugins

So What is protoc plugins? in conext of protoc-jar-maven-plugin ?

**Comment by os72** [comment]
protoc-jar-maven-plugin helps with codegen by invoking protoc. protoc itself can be extended with plugins to support languages that aren't built-in. Eg, protoc-gen-dart.exe, protoc-gen-grpc-java.exe, etc

**Comment by paulvi** [comment]
OK, that is plugins of protoc itself.
