### ISSUE TITLE
Wrong default output directory

### ISSUE THREAD

**Issue by mwillema** [os72/protoc-jar-maven-plugin#3]
In the [ProtocJarMojo at line 100] (https://github.com/os72/protoc-jar-maven-plugin/blob/master/src/main/java/com/github/os72/protocjar/maven/ProtocJarMojo.java#L100) it is said that the default output directory is `${project.build.directory}/generated-sources/protobuf` but actually it is `${project.build.directory}/generated-sources`.

The erroneous code is in [ProtocJarMojo at line 182 and 183] (https://github.com/os72/protoc-jar-maven-plugin/blob/master/src/main/java/com/github/os72/protocjar/maven/ProtocJarMojo.java#L182-L183).

If you want I can fix this and create a pull request.

**Comment by os72** [comment]
Ok will fix the documentation

**Comment by mwillema** [comment]
Shouldn't the code be fixed instead of the doc? I think generating the protobuf classes in a protobuf folder by default makes sense, especially if one generates other stuff as well.

**Comment by os72** [comment]
Nah, it's been like this forever. Changing behavior would be intrusive. Note that you can control it both by overriding it and via package name in .proto files

**Comment by ibauersachs** [comment]
Note that using `generated-sources` directly violates Maven conventions and confuses IntelliJ.

**Comment by os72** [comment]
Yes, perhaps unfortunate, but a change can break existing clients

**Comment by ibauersachs** [comment]
So what? Things change. Especially if you update a version number in Maven... but:
If you consider changing it for a major version number, then it should probably be before Protobuf 3 is final (whenever that may be).
