### ISSUE TITLE
Consider adding integration tests

### ISSUE THREAD

**Issue by electrum** [os72/protoc-jar-maven-plugin#31]
Great work on this project! I love how it has embedded versions of protoc for different platforms and doesn't require on to be pre-installed.

I noticed the project doesn't have any integration tests. Having written some minor Maven plugins myself, I know this can be difficult, so I wanted to point out a new relatively new way to do it that's much easier than the old ways: http://takari.io/book/70-testing.html

Here are some examples:

* https://github.com/airlift/sphinx-maven-plugin/blob/master/src/test/java/io/airlift/maven/sphinx/TestGenerate.java
* https://github.com/prestodb/presto-maven-plugin/tree/master/src/test/java/com/facebook/presto/maven
* https://github.com/facebook/swift/blob/master/swift-maven-plugin/src/test/java/com/facebook/mojo/SwiftIntegrationTest.java

**Comment by os72** [comment]
Ack. Thanks

**Comment by os72** [comment]
Thanks for the tip. Couldn't get unit tests to work because of all sorts of version incompatibilities. But integration tests were relatively easy to set up. Thanks!
https://github.com/os72/protoc-jar-maven-plugin/tree/master/src/test/projects
