### ISSUE TITLE
Is it knows that outputTargets.outputTarget.addSources defaults to none?

### ISSUE THREAD

**Issue by JanecekPetr** [os72/protoc-jar-maven-plugin#35]
See title. It took me a some time to discover that even though configuration.addSources defaults to "main", the one in outputTargets defaults to "none". Is this on purpose and if yes, would you mind documenting the outputTargets thing a little bit more thouroughly?

(otherwise, THANK YOU for the plugin, it overtook my previously favorite proto plugin)

**Comment by os72** [comment]
Sounds like a bug, they should have the same default

**Comment by os72** [comment]
I don't think there is a bug, in my test it defaults to "main"

Code: https://github.com/os72/protoc-jar-maven-plugin/blob/master/src/main/java/com/github/os72/protocjar/maven/OutputTarget.java#L27

**Comment by JanecekPetr** [comment]
Right, I'm sorry, it does actually do the right thing. I must have invoked my commands on the wrong project or done something similarly silly.

Thanks for your time.
