### ISSUE TITLE
Make protoc version 3.0 available through the plugin

### ISSUE THREAD

**Issue by seh** [os72/protoc-jar-maven-plugin#4]
As previously mentioned in #1, please consider publishing a version of the Maven plugin that will use your [_protoc-jar_](https://github.com/os72/protoc-jar) version 3.0.0(-a3), so that we'll have the "proto3" syntax available.

It looks like it may be as "simple" as creating a new branch and changing a few dependency versions in the POM, as well as updating the documentation to mention the new version. But then there's also the matter of releasing the artifact.

Thanks for providing this plugin. It's proven to be easy to use.

**Comment by seh** [comment]
Related issue: os72/protoc-jar#2.

**Comment by os72** [comment]
Will have a look. Expect a new config parameter to control the protoc version since the new jar will contain all flavors now

**Comment by seh** [comment]
Fantastic. If there's anything you'd like me to try to help this along, please let me know. I was intending to figure out how you maintain your separate branches, and how they relate to what's on the `master` branch.

**Comment by os72** [comment]
Pushed 3.0.0-a3-SNAPSHOT, could you give it a try (clone, build, try)? It will run latest bundled protoc, unless you specify `<protocVersion>` under `<configuration>`

**Comment by seh** [comment]
I'm able to build and use the version 3 plugin without any problems. I didn't exercise trying to change the version used by the _protoc_ compiler; using the latest version is my intention.

One suggestion for documentation: The generated code requires that the POM declare a compile-time dependency on [the `com.google.protobuf:protobuf-java` artifact](http://mvnrepository.com/artifact/com.google.protobuf/protobuf-java).

**Comment by os72** [comment]
Released 3.0.0-a3
