### ISSUE TITLE
Up To Date Checks

### ISSUE THREAD

**Issue by amarchanka** [os72/protoc-jar-maven-plugin#41]
It would be nice to have up-to-date check like jaxb2 plugin has.
https://github.com/highsource/maven-jaxb2-plugin/wiki/Up-To-Date-Checks

**Comment by jon-hanson** [comment]
+1 We're using a Maven multi-module build, where the proto defs are in one of the modules. Every time we build the project it recompiles all of the proto files. Having some form of timestamp dependency checking to avoid unnecessarily recompiling proto files would be useful.

**Comment by os72** [comment]
Released in version 3.7.0.1

**Comment by amarchanka** [comment]
It is work only with modification!
I have to add
        <plugin>
            <groupId>org.codehaus.mojo</groupId>
            <artifactId>build-helper-maven-plugin</artifactId>
            <executions>
                <execution>
                    <phase>generate-sources</phase>
                    <goals>
                        <goal>add-source</goal>
                    </goals>
                    <configuration>
                        <sources>
                            <source>${project.build.directory}/generated-sources/proto</source>
                        </sources>
                    </configuration>
                </execution>
            </executions>
        </plugin> 

Could you leave adding source classpath in case when generation skipped?

**Comment by os72** [comment]
Hmm I see, this requires some more serious refactoring. Reopening..

**Comment by os72** [comment]
@amarchanka, could you try 3.7.0.2-SNAPSHOT?

**Comment by amarchanka** [comment]
Ok, I'll try! Thanks!

**Comment by amarchanka** [comment]
Ok, work fine for me. Waiting for release!

My project under 11 JDK, so it is not easy to build your project. 11 doesn't support 1.5 JDK.

**Comment by os72** [comment]
Thanks. (I've used JDK 1.7 and 1.8. Haven't tried 11 yet, I'll have a look. I'm trying to keep this compatible as far back as possible)

**Comment by os72** [comment]
Released version 3.7.0.2

**Comment by amarchanka** [comment]
Thanks!
