### ISSUE TITLE
Add .proto files to classpath

### ISSUE THREAD

**Issue by mwillema** [os72/protoc-jar-maven-plugin#44]
Is there a way to instruct the plugin to add the .proto files into the JAR at build time? So that the .proto files can be found on the classpath, like in ```protobuf-java-3.3.1.jar ``` where the standard types are located in ```google.protobuf```.

**Comment by os72** [comment]
For the standard types you can specify `<includeStdTypes>true</includeStdTypes>` (they come bundled with the plugin)

**Comment by mwillema** [comment]
I know but what I mean here is to have any given set of .proto files added to the built JAR archive. So that we can distribute the JAR file and the .proto files come bundled with it.

**Comment by os72** [comment]
Sorry, I first misread this as the same as issue #19. Shouldn't the packaging step take care of this?

**Comment by RishuK** [comment]
@os72  which packaging step?

**Comment by richslaughter** [comment]
I also need the ability to include the source .proto files in the generated jar file.

@os72 is this something protoc-jar-maven-plugin can do inherently?

It would also be useful to include the standard types which are included with <includeStdTypes>.

**Comment by os72** [comment]
@richslaughter - ack. No, this feature needs to be added, haven't had time or help. Will look into it
@RishuK - I don't know if assembly plugin could be used as workaround at least

**Comment by os72** [comment]
@mwillema @RishuK @richslaughter 
Hi guys, I've added property `addProtoSources` (all/inputs/none), can you give it a try?

I thought it might be important to be able to filter on "inputs" (inputDirectories) vs "all" (inputs and includes). Is finer-grained control needed?

**Comment by os72** [comment]
Released 3.5.1
