### ISSUE TITLE
Plugin does not work for several Directories with dependent Protos

### ISSUE THREAD

**Issue by schulz-m** [os72/protoc-jar-maven-plugin#50]
Hello everyone,

I have two proto files in two different directories whereas one is dependent on the other and I don't get it to work, it seems to me that there might be a bug how imports are handled - either by the protoc compiler or the maven plugins (I have the same issue with the [protobuf maven plugin](https://github.com/xolstice/protobuf-maven-plugin). My directory structure looks approximately like this:

```
.
├── pom.xml
├── src
│   └── main
│       ├── java
│       │   └── ...
│       ├── proto
│       │   └── service.proto
│       └── resources
│           └── submodule
│               ├── protobuf
│               │   └── framework.proto
```

I need to preserve this directory structure and I also want to use the same `framework.proto` in other maven modules by accessing the resource path ideally.

The `service.proto` is using definitions of the framework by importing: `import "framework.proto";`

Now I tried to build the protobuf classes by copying the examples on the github site:

```xml
<plugin>
                <groupId>com.github.os72</groupId>
                <artifactId>protoc-jar-maven-plugin</artifactId>
                <version>3.5.1.1</version>
                <executions>
                    <execution>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>run</goal>
                        </goals>
                        <configuration>
                            <addProtoSources>all</addProtoSources>
                            <includeStdTypes>true</includeStdTypes>
                            <includeDirectories>
                                <include>${basedir}/src/main/resources/submodule/protobuf</include>
                            </includeDirectories>
                            <inputDirectories>
                                <include>${basedir}/src/main/proto</include>
                            </inputDirectories>
                            <outputTargets>
                                <outputTarget>
                                    <type>java</type>
                                </outputTarget>
                                <outputTarget>
                                    <type>grpc-java</type>
                                    <pluginArtifact>io.grpc:protoc-gen-grpc-java:1.0.1</pluginArtifact>
                                </outputTarget>
                            </outputTargets>
                        </configuration>
                    </execution>
                </executions>
</plugin>
```

Now the compilation is failing because the `ServiceOuterClass` : `cannot find symbol
[ERROR] symbol: variable Framework`. Inspecting the generated sources on `target/generated-sources`, I realised that `Framework.java` was not generated, so I added the path to the `<inputDirectories>` - That will indeed generate the Java class, but the Java imports on the `ServiceOuterClass` will still be wrong unfortunatelly.

I have seen many issues on Stackoverflow and Github concerning the imports of other proto-files but unfortunatelly no good solution - any tipps are appreciated!

**Comment by schulz-m** [comment]
Note: It does work if both the `service.proto` and `framework.proto` are defined in the same `package` AND both directories are defined as `inputDirectories`, which IMHO shows that the Java dependencies are not generated correctly (might be a problem of protoc and not of the plugin itself though ...)

**Comment by os72** [comment]
Could you provide the log? We should be able to see whether the plugin prepares the protoc invocation correctly or not

**Comment by schulz-m** [comment]
@os72 Please excuse the belated response, I just had a look into this again. So I did the mistake of not defining a `package`in the `framework.proto` which leads to wrongly generated imports, as all dependent protos need to have a proper namespace.

Additionally, the protoc compiler relies on the protos that are included to be built "somewhere" in the class path, the log is approximately like:
```
[INFO]     Processing (java): service.proto
protoc-jar: executing: [/var/folders/q0/8cy4jxy13ml92frk1jdpmrxw0000gn/T/protoc1700105763840564952.exe, -I/src/main/resources/submodule/protobuf, -I/src/main/proto, --java_out=target/generated-sources, src/main/proto/service.proto]
```

Which is fair enough I guess, the developer just has to be aware of this, so I would propose to close the issue :-)

**Comment by os72** [comment]
Ok great :)
