### ISSUE TITLE
Support for Protocol Buffers 3.6

### ISSUE THREAD

**Issue by alfonx** [os72/protoc-jar-maven-plugin#53]
[Protocol Buffers Version 3.6.0 has been released](https://github.com/google/protobuf/releases/tag/v3.6.0). Will it be compatible with this protoc-jar-maven-plugin?

The Readme.md currently states: 

> Supports protoc versions 2.4.1, 2.5.0, 2.6.1, 3.5.1.

Support for 3.6 would be a greatly appreciated feature!

**Comment by os72** [comment]
The "official" support statement is a bit conservative :) Those are the binaries embedded directly in the jar, and yes I upgrade them with new versions

But the plugin actually supports any version it can download from maven central (google or os72). So 3.6.0 should just work, give it a try

**Comment by os72** [comment]
Released protoc-jar-maven-plugin 3.6.0

**Comment by os72** [comment]
Released protoc-jar-maven-plugin 3.6.0.1

**Comment by alfonx** [comment]
Works great, thanks
