### ISSUE TITLE
Using proto files which are organized inside directories, but referencing each other, is not possible

### ISSUE THREAD

**Issue by d4ndel1on** [os72/protoc-jar-maven-plugin#58]
Currently the single files are processed inside their parent folders.
I've got a usecase in which the files are inside directories but reference relative to the input directory like following illustration:
- src
  - main
    - protobuf
      - module_1
        - file1.proto (imports "module_2/file2.proto")
      - module_2
        - file2.proto

The execution fails because "module_2/file2.proto" can't be found inside module_1.
To address this issue a flag could be added which will set the working directory for every protoc execution to the related input directory.
No breaking change needs to be done if the default value is set to false.
I already created a pull request:
[Pull Request](https://github.com/os72/protoc-jar-maven-plugin/pull/57)

**Comment by os72** [comment]
Just add `includeDirectories`, doesn't that work?
```
<includeDirectories>
	<include>src/main/protobuf</include>
</includeDirectories>
```

**Comment by d4ndel1on** [comment]
You are right. That's even easier. Thanks.
Issue can be closed.
