### ISSUE TITLE
Where to put proto files?

### ISSUE THREAD

**Issue by sensei-wu** [os72/protoc-jar-maven-plugin#59]
I have proto files under `/src/main/proto`, but the below configuration did not work

```
<configuration>
                            <addProtoSources>all</addProtoSources>
                            <includeMavenTypes>direct</includeMavenTypes>
                            <includeDirectories>
                                <include>src/main/proto</include>
                            </includeDirectories>
</configuration>
```

Only if I create `/src/main/protobuf` directory and put files there, they are picked up. Any suggestions?

**Comment by os72** [comment]
Yes, `<inputDirectories>`
```
 <inputDirectories>
   <include>src/main/proto</include>
 </inputDirectories>
```

**Comment by sensei-wu** [comment]
From the doc. as I understood. default input dir. is `src/main/protobuf`. If I want additional input directories, I need to use like below

```<includeDirectories>
					<include>src/main/more_proto_imports</include>
				</includeDirectories>
				<inputDirectories>
					<include>src/main/protobuf</include>
				</inputDirectories>```

I put my sources under `src/main/proto` and added the following config:

```
<configuration>
                            <addProtoSources>all</addProtoSources>
                            <includeMavenTypes>direct</includeMavenTypes>
                            <includeDirectories>
                                <include>src/main/proto</include>
                            </includeDirectories>
                            <inputDirectories>
                                <include>src/main/protobuf</include>
                            </inputDirectories>
                        </configuration>
```

The files under `src/main/proto` were ignored! I also tried putting it under `<inputDirectories>` like you suggested, still dod not work

**Comment by os72** [comment]
Looks like you used `src/main/protobuf` in your config, not `src/main/proto`. Otherwise it looks good

**Comment by os72** [comment]
Assuming closed
