### ISSUE TITLE
Contribute this Maven plugin to protobuf project

### ISSUE THREAD

**Issue by nandorKollar** [os72/protoc-jar-maven-plugin#62]
Hi @os72 ,

I was searching for an "official" protobuf plugin for Maven, but I couldn't find any. You did a great job by implementing this version, it seems really useful, but unfortunately since it is not part of the official propobuf project, we can't use it. Did you think of contributing it to protobuf project?

**Comment by JanecekPetr** [comment]
> "since it is not part of the official propobuf project, we can't use it"

???

An internal policy allowing to only use 3rd party libraries with their own tooling, but not other 3rd party tooling? That sounds arbitrary :(.

I'm not this plugin's author, I'm only interested in the rationale behind this, I'd like to see what drives this request. If your case is common enough, perhaps the author might consider doing this. As it currently stands, though, it sounds like a silly policy of a company that should, honestly, be solved by changing the policy.
