### ISSUE TITLE
have core dump file when use protoc in linux

### ISSUE THREAD

**Issue by wenweihu86** [os72/protoc-jar-maven-plugin#63]
[INFO] --- protoc-jar-maven-plugin:3.6.0.1:run (generate-sources) @ brpc-java ---
[INFO] Protoc version: 2.5.0
protoc-jar: protoc version: 2.5.0, detected platform: linux-x86_64 (linux/amd64)
protoc-jar: embedded: bin/2.5.0/protoc-2.5.0-linux-x86_64.exe
protoc-jar: executing: [/tmp/protocjar6053145344578931019/bin/protoc.exe, --version]
[INFO] Protoc command: /tmp/protocjar6053145344578931019/bin/protoc.exe
[INFO] Additional include types: /tmp/protocjar1509145097883442087/include

**Comment by wenweihu86** [comment]
centos 4.3

**Comment by os72** [comment]
Assuming closed
