### ISSUE TITLE
[Question] Is platform dependency taken care?

### ISSUE THREAD

**Issue by Selvaguru** [os72/protoc-jar-maven-plugin#7]
I believe Proto Buffers Compiler (protoc) is platform dependent. This plugin will download the appropriate protoc (according to the platform) and compile .proto files to .java files?

**Comment by os72** [comment]
The plugin jar actually contains protoc binaries (2.4.1 - 3.0.0) for Linux, Mac/OSX, and Windows. At runtime it detects the platform and executes the corresponding binary
