### ISSUE TITLE
change directory path of protoc.exe from c:\users\...\temp to other directory

### ISSUE THREAD

**Issue by deepakThedeveloper** [os72/protoc-jar-maven-plugin#73]
when I am executing command maven install,  by default the c:\users\...\temp directory is being used for executing protoc.exe file.
As companies group policy is applied on this directory, the .exe file from this c:\\temp can't be executed.

I want to change this path. I want the protoc.exe files to be in some other folder and not in c:\users\...\temp path.

This is my pom.xml

<plugins>
<plugin>
<groupId>com.github.os72</groupId>
<artifactId>protoc-jar-maven-plugin</artifactId>
<version>2.5.0.1</version>
<executions>
<execution>
<phase>generate-test-sources</phase>
<goals>
<goal>run</goal>
</goals>
<configuration>
<addSources>test</addSources>
<outputDirectory>target/generated-test-sources</outputDirectory>
<inputDirectories>
<include>src/test/protobuf</include>
</inputDirectories>
</configuration>
</execution>
</executions>
</plugin>
</plugins>

Can anyone please help me with some pointers to change the path?

**Comment by os72** [comment]
Could you try a newer version? (protoc 2.5.0 is still supported)
A feature for your scenario is already implemented (#39)

**Comment by deepakThedeveloper** [comment]
I have tried  changing the version from 2.5.0.1 to 3.3.0.1. problem is that was causing runtime error in other classes. I am sure there might be many upgradation in methods, signatures in 3.3.0.1 version, and the methods used in other classes are of 2.5.0.1 so, it is causing failure.

Also I have tried with latest version 3.7.0.2 but it didn't helped as well

**Comment by deepakThedeveloper** [comment]
As I am on windows , I have tried to change  java.io.tmpdir path with following command
java -Djava.io.tmpdir=E:\tmpFolder

but is not returning any output.

**Comment by os72** [comment]
I'm guessing you haven't specified `protocVersion` (to 2.5.0)? Output log might help

**Comment by os72** [comment]
Assuming closed
