### ISSUE TITLE
Support custom classifiers extensions for plugin artifacts

### ISSUE THREAD

**Issue by thesamet** [os72/protoc-jar-maven-plugin#75]
ScalaPB (code generator for Scala) is now publishing a standalone script that can be used as a plugin. For Windows, the extension must be `.bat`. For all unix-like systems, it can be anything and we are using `.sh`. See the layout here: http://central.maven.org/maven2/com/thesamet/scalapb/protoc-gen-scalapb/0.9.0-M5/

Alternatively, since the plugin is JVM based, it would be nice to be able to provide to run the artifact through a `mainClass` https://www.xolstice.org/protobuf-maven-plugin/examples/protoc-plugin.html so all the platform specific scripts become unnecessary.

**Comment by os72** [comment]
If I understand the question correctly, this is already supported via `pluginArtifact` and `pluginPath`
Example: http://os72.github.io/protoc-jar-maven-plugin/run-mojo.html#outputTargets

**Comment by thesamet** [comment]
Currently resolveArtifact hard codes the exe extension, and that the Maven artifact is the operating system name. The ask is to be able to customize that

**Comment by os72** [comment]
I see. Convenience backfires in this case. Need to look..
How about the `mainClass` option, how would you want the plugin section to look like?

**Comment by thesamet** [comment]
The gradle protobuf plugin takes this syntax: `com.thesamet.scalapb:protoc-gen-scalapb:${scalapbVersion}:windows@bat`

https://github.com/scalapb/gradle-demo/blob/master/build.gradle#L44

I learned it from https://github.com/google/protobuf-gradle-plugin/blob/87b3caeacef74d4daa6bfc11ed6d0ef7876b4b92/src/main/groovy/com/google/protobuf/gradle/ToolsLocator.groovy#L54 - I think it is undocumented.

For the mainClass option, I think it's better to have another property rather than encode it in the artifact name - over time you might want to have things like `jvmArgs` and `args`. See https://www.xolstice.org/protobuf-maven-plugin/examples/protoc-plugin.html for `mainClass`, `args and so on.

**Comment by os72** [comment]
Could you try 3.7.1.1-SNAPSHOT (for the basic request)?

**Comment by thesamet** [comment]
Thanks for the quick turnaround! Where is the SNAPSHOT published to? I was looking https://oss.sonatype.org/content/repositories/snapshots/com/github/os72/protoc-jar-maven-plugin/ but couldn't find it.

**Comment by os72** [comment]
Oh I thought you would just clone the repo and build locally. But I've published the SNAPSHOT now

**Comment by thesamet** [comment]
Works! Thank you so much. Note that the extension and classifier seem to be swapped compared to the URL format and the format in protobuf-gradle.

`com.thesamet.scalapb:protoc-gen-scalapb:0.9.0-M5:sh:unix` becomes`http://central.maven.org/maven2/com/thesamet/scalapb/protoc-gen-scalapb/0.9.0-M5/protoc-gen-scalapb-0.9.0-M5-unix.sh`. I think it would be less surprising if the parameter order was the same. . But that's a nit - great work and thanks for implementing this so quickly. Once this gets published I'll update ScalaPB documentation to use this.

**Comment by os72** [comment]
Yes that's by design (kinda) -- it's the same order as expected by `protobuf-maven-plugin` (eg, `<pluginArtifact>io.grpc:protoc-gen-grpc-java:1.21.0:exe:${os.detected.classifier}</pluginArtifact>`)

And I'm guessing that's simply because it's the order given by maven API `artifactFactory.createDependencyArtifact` :) (see https://github.com/os72/protoc-jar-maven-plugin/commit/264259686ef9652c92314b72c667274c7ecb1b74)

**Comment by os72** [comment]
Released protoc-jar-maven-plugin 3.8.0
