### ISSUE TITLE
includeMavenTypes and compileMavenTypes cannot be used together

### ISSUE THREAD

**Issue by shartte** [os72/protoc-jar-maven-plugin#77]
When wanting to compile proto files from dependencies, but also include those types, the plugin will fail because the extraction path is not added first to the include path.

Command-Line (stripped the directory prefix):
```
protoc-jar: executing: [Temp\protocjar3507522335255123570\bin\protoc.exe, -ITemp\protocjar1871759504006407564\include, -ITemp\protocjar1871759504006407564\mvncompile, [...], Temp\protocjar1871759504006407564\mvncompile\additional_infos_message.proto]
```

Result:
```
Temp\protocjar1871759504006407564\mvncompile\additional_infos_message.proto: Input is shadowed in the --proto_path by "Temp/protocjar1871759504006407564/include/additional_infos_message.proto".  Either use the latter file as your input or reorder the --proto_path so that the former file's location comes first.
```

Possible solution: If `compileMavenTypes` is used, prepend it to the proto include path so that additionally using includeMavenTypes is not needed. Currently, including files extracted via compileMavenTypes is not possible.

**Comment by os72** [comment]
I'm not sure what your configuration looks like, but there is a working test that does exactly that:
https://github.com/os72/protoc-jar-maven-plugin/blob/master/src/test/projects/mvn-compile-test/pom.xml

Could you check and maybe show how to reproduce your issue

**Comment by shartte** [comment]
Yeah I'll do so. Where does the test you linked take it's own protobuf sources from?

**Comment by os72** [comment]
The test project only uses protos from protobuf-java. Feel free to modify it if it helps show your issue

**Comment by os72** [comment]
Assuming closed
