### ISSUE TITLE
Is it possible to import protos using --proto_path? 

### ISSUE THREAD

**Issue by vagenius** [os72/protoc-jar-maven-plugin#8]
Hey. 
It seems to me that it's impossible for now to import other protos from different locations using --proto_path. If you can implement such feature, it would be nice. I suppose (according the code) that's it's not difficult.
PS: plugin is great:)

**Comment by os72** [comment]
It's there, `includeDirectories` config section. It populates `-I` which is the same as `--proto_path`

**Comment by vagenius** [comment]
Oh, you are right. It works. Thank you very much.
