### ISSUE TITLE
[help]Is there a way to save the downloading protoc process?

### ISSUE THREAD

**Issue by Nov11** [os72/protoc-jar-maven-plugin#83]
Here's the situation:

We are depending on this awesome plugin to compile proto files during build process.
Downloading protoc from central maven takes 1:30 min on average when the plugin is invoked on a CI machine. (Our network connection is not that good.) And that 1:30 min looks like something could be saved.

In order to do this, I come up with an idea to store the plugin and its relative dependencies like protoc into our project as maven local dependency. 

Here are my questions:
1. Is this applicable? If so which files should I save into the project?
2. Any better suggestion?

**Comment by Nov11** [comment]
Forgot to mention, we are using protobuf 3.5.1

**Comment by os72** [comment]
Either maven or the plugin will save a local copy. What's your configuration?

**Comment by Nov11** [comment]
Here's our config of the plugin.
`<build>
        <plugins>
            <plugin>
                <groupId>com.github.os72</groupId>
                <artifactId>protoc-jar-maven-plugin</artifactId>
                <version>3.5.0</version>
                <executions>
                    <execution>
                        <id>java</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>run</goal>
                        </goals>
                        <configuration>
                            <protocVersion>3.5.1</protocVersion>
                            <includeDirectories>
                                <includeDirectory>src/main/proto</includeDirectory>
                            </includeDirectories>
                            <inputDirectories>
                                <inputDirectory>src/main/proto</inputDirectory>
                            </inputDirectories>
                            <outputTargets>
                                <outputTarget>
                                    <type>java</type>
                                </outputTarget>
                            </outputTargets>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
`
The project is copied into a new docker image first. Then 'mvn install' is executed in the file system of that image. So I think the plugin's downloading process will grab and cache the binary inside that docker image. Since the binary is not saved into any base images, each time a new merge request triggers a CI process, the plugin sees no cached binary and starts to download it. The very downloading time is what I want to save.

**Comment by os72** [comment]
You could just upgrade to 3.5.1, which has protoc 3.5.1 embedded in the jar
https://github.com/os72/protoc-jar-maven-plugin/blob/master/RELEASE_NOTES.md

**Comment by Nov11** [comment]
Thank you!
