### ISSUE TITLE
a nasty issue just came up

### ISSUE THREAD

**Issue by ThomasSunKai** [os72/protoc-jar-maven-plugin#84]
protoc-jar: caught exception, retrying: java.io.IOException: Cannot run program "*****bin\protoc.exe": CreateProcess error=5, ?????,i searched for the error that anyone could meet,but it seems like i'm now the only who are stuck here,could u plz help me? some related info:Scala Bindings ..................................... FAILURE

**Comment by os72** [comment]
This looks like protoc running on incompatible OS. Is it still open?

**Comment by os72** [comment]
Assuming resolved
