### ISSUE TITLE
Pure Java plugin artifact

### ISSUE THREAD

**Issue by ennerf** [os72/protoc-jar-maven-plugin#85]
Is there a way to define a custom plugin artifact that is not an `.exe` but a `.jar` file with an executable main method?

```XML
<outputTargets>
	<outputTarget>
		<type>java</type>
	</outputTarget>
	<outputTarget>
		<type>grpc-java</type>
		<pluginArtifact>io.grpc:protoc-gen-grpc-java:1.0.1</pluginArtifact>
	</outputTarget>
</outputTargets>
```

Alternatively, it'd be nice if we could specify a `.zip` file that contains appropriately named shell/bash scripts. That would also make it work for plugins written in other languages like Python.

**Comment by os72** [comment]
There is `pluginPath`, doesn't that work via a shell script like you suggest?

**Comment by ennerf** [comment]
The `pluginPath` seems to have some issues with scripts, even when calling protoc directly. I've only ever gotten scripts to run if they are on the `$PATH`. In any case, the bigger pain point is that users need to download and unzip it somehow.

I've found a workaround using the `maven-antrun-plugin`, but it'd be great if this functionality could be added to the plugin directly. That'd make it much easier to use plugins that are not bundled as `.exe` on Maven Central (e.g. [Swift](https://github.com/apple/swift-protobuf/blob/master/Documentation/PLUGIN.md), [NanoPB](https://jpa.kapsi.fi/nanopb/download/), and probably most others)

Sample config:

```XML
<build>
    <plugins>

        <!-- Downloads generator plugin -->
        <plugin>
            <artifactId>maven-antrun-plugin</artifactId>
            <version>1.8</version>
            <executions>
                <execution>
                    <id>download-protoc-plugin</id>
                    <phase>generate-sources</phase>
                    <configuration>
                        <tasks>
                            <get src="https://github.com/HebiRobotics/QuickBuffers/releases/download/1.0-alpha3/protoc-gen-quickbuf-1.0-alpha3.zip"
                                 dest="../protoc-gen-quickbuf.zip" skipexisting="true" verbose="on"/>
                            <unzip src="../protoc-gen-quickbuf.zip" dest=".." overwrite="false"/>
                        </tasks>
                    </configuration>
                    <goals>
                        <goal>run</goal>
                    </goals>
                </execution>
            </executions>
        </plugin>

        <!-- Calls protoc.exe and generates messages -->
        <plugin>
            <groupId>com.github.os72</groupId>
            <artifactId>protoc-jar-maven-plugin</artifactId>
            <version>3.8.0</version>
            <executions>
                <execution>
                    <phase>generate-sources</phase>
                    <goals>
                        <goal>run</goal>
                    </goals>
                    <configuration>
                        <protocVersion>3.9.1</protocVersion>

                        <!-- plugin configuration, options, etc. -->
                        <outputTargets>
                            <outputTarget>
                                <type>quickbuf</type>
                                <outputOptions>store_unknown_fields=false</outputOptions>
                            </outputTarget>
                        </outputTargets>

                    </configuration>
                </execution>
            </executions>
        </plugin>

    </plugins>
</build>
```

**Comment by os72** [comment]
I think prepping the protoc plugins separately actually sounds "right". And `pluginPath` should be able to trigger any external executable. (It's actually controlled by `protoc` natively, we just pass the path)

Re pure Java, I'm not quite sure what we could do, again the execution is controlled by `protoc`..

**Comment by ennerf** [comment]
Regarding my use case, I created the issue before I found a workaround. Users will need to modify the configuration if they are already running the ant plugin, but it is workable as is.

For pure Java plugins it'd probably have to generate wrapper scripts that can get found by `protoc` and then executes the Java plugin. The scripts are pretty simple, e.g., `java -jar <jar>`.

Specifying a `pluginPath` works for `.exe` files, but it seems to have issues with wrapper scripts. The problem also exists when calling `protoc` manually, so it's not an issue with the maven plugin. If I get a chance to debug it further I'll open an issue there.

I'll go ahead and close this issue for now.

**Comment by ennerf** [comment]
Looking at this again, the problem is that `protoc` searches the PATH for matching file names with different extensions (e.g. `.exe` and `.bat`), but the `pluginPath` needs to specify the exact executable.

Would it be feasible to add another parameter that sets the PATH environment variable on the ProcessBuilder?

**Comment by ennerf** [comment]
I think exposing the path would still be a good feature, but I wasn't sure how to best do a PR as it touches through to dependency projects. I tried a bunch of other workarounds, but eventually gave up and used the supported way with graal native executables released to maven central.

`<pluginArtifact>us.hebi.quickbuf:protoc-gen-quickbuf:1.0.0</pluginArtifact>`

works like a charm 👍 closing again.
