### ISSUE TITLE
built-in types

### ISSUE THREAD

**Issue by arashbi** [os72/protoc-jar-maven-plugin#86]
It seems that plugin cannot find the google build in types. like google.proto.timestamp. Do I have to manually provide them?

**Comment by os72** [comment]
They can be included from the plugin itself (option `includeStdTypes`) or from your `protobuf-java` dependency (option `includeMavenTypes`)
http://os72.github.io/protoc-jar-maven-plugin/run-mojo.html

**Comment by arashbi** [comment]
Thanks!
