### ISSUE TITLE
preserve native plugin artifact extension

### ISSUE THREAD

**Issue by thesamet** [os72/protoc-jar-maven-plugin#89]
When specifying plugin artifact such as this:

    <pluginArtifact>com.thesamet.scalapb:protoc-gen-scala:0.9.6:bat:windows</pluginArtifact>

protoc-jar doesn't preserve the extensions (`bat` in this case), and uses `exe`. As it turns out, Windows is picky about this, and wouldn't execute the plugin in that case.

The expected behavior would be that the artifact extension is preserved when it is downloaded.

**Comment by os72** [comment]
Fixed in 3.11.4
