### ISSUE TITLE
Golang outpuTarget

### ISSUE THREAD

**Issue by franklinlindemberg** [os72/protoc-jar-maven-plugin#90]
Hi guys, I really enjoyed this project. We've been using for a while for creating java classes from protobuf.

But now we have some applications in golang that need to use the same data definition. I know I can copy the proto and generate them using a go client, but it would be nice that all code generation was done at the same time, to guarantee consistency.

Is there any reason why go is not accepted?
If you think it is possible to add and would make sense, I can give a hand and try to create a PR for you.

Let me know what you think!

**Comment by os72** [comment]
I think if `protoc-gen-go` is installed you can simply specify
```
<outputTarget>
  <type>go</type>
</outputTarget>
```
https://developers.google.com/protocol-buffers/docs/reference/go-generated

**Comment by franklinlindemberg** [comment]
Indeed it works! I think the first time I tried I didnt have protoc-gen-go installed!

In the outputTargets documentation it doesn't mention it.
```
Type options: "java", "cpp", "python", "descriptor" (default: "java"); for proto3 also: "javanano", "csharp", "objc", "ruby", "js"
```

In case you think the documentation should be updated.

Tks!
