### ISSUE TITLE
Compilation fails if you use Any or any other core protobuf dependencies

### ISSUE THREAD

**Issue by arecmetafora** [os72/protoc-jar-maven-plugin#93]
The plugin fails if you import a google protobuf dependency, as `google/protobuf/any.proto`.

I checked the source and apparently the plugin is building each imported file individually. However, if you use the parameter `--proto_path` you can build them all at once, and apparently all google dependencies are imported for free.

Example:

```
protoc.exe --java_out=lite:Java --proto_path=schema proto1.proto proto2.proto proto3.proto
```

**Comment by os72** [comment]
Use
```<includeStdTypes>true</includeStdTypes>```
or
```<includeMavenTypes>direct</includeMavenTypes>```

The second form may be a little cleaner as it would take the protos straight from `protobuf-java` dependency. It would also add protos found in any other direct dependencies (like other common protos), which tends to be desirable

**Comment by arecmetafora** [comment]
That worked, thanks @os72. It may be useful to add this information in the main doc section on Gitlab (the core examples you share)
