### ISSUE TITLE
Protobuf well-known types

### ISSUE THREAD

**Issue by AeonDave** [os72/protoc-jar-maven-plugin#94]
Hello,
is possible to add well-known types import like Any and Timestamp?
[ERROR] /proto.proto [0:0]: google/protobuf/any.proto: File not found. 
[ERROR] /proto.proto [0:0]: google/protobuf/timestamp.proto: File not found.

i guess i have to add something like "--include_std_types" but i don't know where.

Ty

**Comment by os72** [comment]
See #93 and/or documentation

Use
<includeStdTypes>true</includeStdTypes>
or
<includeMavenTypes>direct</includeMavenTypes>

The second form may be a little cleaner as it would take the protos straight from protobuf-java dependency. It would also add protos found in any other direct dependencies (like other common protos), which may be desirable

**Comment by AeonDave** [comment]
thanks for the clarification!
maybe add it in the examples!

Bye
